import { all } from 'redux-saga/effects';
import { combineReducers } from 'redux';

// 배송 가능/불가
import {
  helperCompanyList,
  memberCompanyList,
  branchCompanyList,
  areaList,
  searchAreaList,
  insertArea,
  updateArea,
  deleteArea,
  useArea,
  helperCompanyListSaga,
  memberCompanyListSaga,
  branchCompanyListSaga,
  insertAreaSaga,
  updateAreaSaga,
  deleteAreaSaga,
  UseAreaSaga,
  areaListSaga,
  searchAreaListSaga,
} from './delivery';

import {
  searchShopLocList,
  searchShopLocListSaga,
  getShopItemList,
  shopItemListSaga,
  shopAddrSaga,
  setShopAddr,
} from './shopLocation';

// 목적지 관리
import {
  destList,
  destListSaga,
  deleteDestList,
  deleteDestListSaga,
  insertDestList,
  insertDestListSaga,
  CdestList,
  CdestListSaga,
  copyDestList,
  copyDestListSaga,
  searchDestPrivate,
  destPrivateSaga,
  searchPointPrivate,
  pointPrivateSaga,
  copyDataPrivate,
  copyPrivateSaga,
} from './destination';

// 기사 관제
import {
  cRiderList,
  cShopList,
  cRiderDrivingList,
  cRiderListSaga,
  cShopListSaga,
  cRiderDrivingListSaga,
} from './rider';

// 지역 공통
import {
  sidoList,
  sidoListSaga,
  gunguList,
  gunguListSaga,
  dongList,
  dongListSaga,
  riList,
  riListSaga,
  cNameShopList,
  cNameShopListSaga,
  getDaumAddr,
  getDaumAddrSaga,
  sendRiderSms,
  sendRSmsSaga,
  insertMSG,
  insertMsgSaga,
} from './common';
import areaStateInfo from './component/area/area';

// 가맹점 좌표
import {
  shopList,
  areaFeeList,
  areaFeeSearchList,
  areaFeeB2BList,
  shopListSaga,
  areaFeeB2BListSaga,
  areaFeeListSaga,
  areaFeeSearchListSaga,
} from './shop';

// 가맹점 구역 요금
import {
  getShopFeeList,
  saveShopFeeAreaList,
  setAreaAmtAdd,
  getCallCenterInfo,
  getCopyShopInfo,
  getAreaAmtList,
  searchShopFeeListSaga,
  saveShopFeeAreaSaga,
  setAreaAmtAddSaga,
  getCallCenterInfoSaga,
  getAreaAmtListSaga,
  getCopyShopInfoSaga,
  deleteAreaFee,
  deleteAreaFeeSaga,
  shopPayCheckSaga,
  cAreaAmtSaga,
  getShopPayCheckExec,
  copyAreaAmtExec,
} from './shopFee';

// 리듀서 조합
const rootReducer = combineReducers({
  destList,
  deleteDestList,
  sidoList,
  gunguList,
  dongList,
  riList,
  areaStateInfo,
  helperCompanyList,
  memberCompanyList,
  branchCompanyList,
  areaList,
  searchAreaList,
  shopList,
  areaFeeList,
  areaFeeSearchList,
  areaFeeB2BList,
  deleteAreaFee,
  searchShopLocList,
  CdestList,
  copyDestList,
  searchDestPrivate,
  searchPointPrivate,
  copyDataPrivate,
  cRiderList,
  cShopList,
  cNameShopList,
  cRiderDrivingList,
  insertArea,
  updateArea,
  deleteArea,
  useArea,
  getShopFeeList,
  saveShopFeeAreaList,
  insertDestList,
  getDaumAddr,
  getShopItemList,
  setShopAddr,
  setAreaAmtAdd,
  getCallCenterInfo,
  getCopyShopInfo,
  getAreaAmtList,
  getShopPayCheckExec,
  copyAreaAmtExec,
  sendRiderSms,
  insertMSG,
});

export default rootReducer;
export type RootState = ReturnType<typeof rootReducer>;

export function* rootSaga() {
  yield all([
    destListSaga(),
    sidoListSaga(),
    gunguListSaga(),
    dongListSaga(),
    riListSaga(),
    deleteDestListSaga(),
    helperCompanyListSaga(),
    memberCompanyListSaga(),
    branchCompanyListSaga(),
    areaListSaga(),
    searchAreaListSaga(),
    shopListSaga(),
    areaFeeListSaga(),
    areaFeeSearchListSaga(),
    areaFeeB2BListSaga(),
    deleteAreaFeeSaga(),
    searchShopLocListSaga(),
    CdestListSaga(),
    copyDestListSaga(),
    destPrivateSaga(),
    pointPrivateSaga(),
    copyPrivateSaga(),
    cRiderListSaga(),
    cShopListSaga(),
    cNameShopListSaga(),
    cRiderDrivingListSaga(),
    searchShopFeeListSaga(),
    saveShopFeeAreaSaga(),
    insertAreaSaga(),
    updateAreaSaga(),
    deleteAreaSaga(),
    UseAreaSaga(),
    insertDestListSaga(),
    getDaumAddrSaga(),
    shopItemListSaga(),
    shopAddrSaga(),
    setAreaAmtAddSaga(),
    getCallCenterInfoSaga(),
    getCopyShopInfoSaga(),
    getAreaAmtListSaga(),
    shopPayCheckSaga(),
    cAreaAmtSaga(),
    sendRSmsSaga(),
    insertMsgSaga(),
  ]);
}
